version: "3.3"

services: 
  a-registro-authenticacion:
    restart: always 
    build: .
    labels: 
      - "traefik.http.routers.a-registro-authenticacion.rule=Host(`a-registro-authenticacion.restoner-api.fun`)"
    networks:
      - backend
    links:
      - redis
      - postgres-master
  redis:
    image: redis:5.0.0
    container_name: master
    ports:
      - "6379:6379"
    networks:
      - backend
  redis-slave:
    image: redis:5.0.0
    container_name: slave
    ports:
      - "6380:6379"
    command: redis-server --slaveof master 6379
    depends_on:
      - redis
    networks:
      - backend
  postgres-master:
    container_name: postgres_db
    restart: always
    image: 'bitnami/postgresql:14.4.0'
    networks:
      - backend
    ports:
      - "5432"
    volumes:
      - 'postgresql_master_data:/bitnami/postgresql'
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - DATABASE_HOST=127.0.0.1
      - POSTGRESQL_REPLICATION_USER=replicacion_usuari4123o_123
      - POSTGRESQL_REPLICATION_PASSWORD=replicacion_contrasenia_asda21qdac2123
      - POSTGRESQL_USERNAME=postgresx
      - POSTGRESQL_PASSWORD=adsfg465WFVFGdsrf3465QWFDSFGH4fsadf4fwedf
      - POSTGRESQL_DATABASE=postgresx
  postgresql-slave:
    image: 'bitnami/postgresql:14.4.0'
    ports:
      - "6432:5432"
    networks:
      - backend
    depends_on:
      - postgres-master
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=replicacion_usuari4123o_123
      - POSTGRESQL_REPLICATION_PASSWORD=replicacion_contrasenia_asda21qdac2123
      - POSTGRESQL_MASTER_HOST=postgres-master
      - POSTGRESQL_PASSWORD=adsfg465WFVFGdsrf3465QWFDSFGH4fsadf4fwedf
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
  pgadmin:
    restart: always
    image: "dpage/pgadmin4"
    networks:
      - backend
    ports:
      - "90:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: adminx@adminx.com
      PGADMIN_DEFAULT_PASSWORD: dsgojq02934jMG4GG436gdgfG346FD
    depends_on:
      - postgres-master
  traefik:
    image: traefik:v2.3.6
    ports: 
      - 80:80
      - 443:443
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/traefik.yml
      - ./acme.json:/acme.json
    networks:
      - backend

networks:
  backend:
    driver: bridge
    ipam: 
      driver: default 

volumes:
  postgresql_master_data:






