version: "3.3"

services: 
  app:
    container_name: restonercomensales_app_servicio_auth_registro
    restart: always 
    build: .
    networks:
      - backend
    ports:
      - "5000:5000"
    links:
      - redis
      - postgres
  redis:
    container_name: redis_db
    restart: always
    image: "redis:6.0.16"
    networks:
      - backend
    ports: 
      - "6000:6379"
  postgres:
    container_name: postgres_db
    restart: always
    image: "postgres:13"
    networks:
      - backend
    ports:
      - "7000:5432"
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=postgresx
      - POSTGRES_PASSWORD=postgresx
      - POSTGRES_DB=postgresx
  pgadmin:
    restart: always
    image: "dpage/pgadmin4"
    networks:
      - backend
    ports:
      - "90:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: adminx@adminx.com
      PGADMIN_DEFAULT_PASSWORD: adminx
    depends_on:
      - postgres
networks:
  backend:








